# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:8.11.3

pipelines:
  default:
    - step:
        name: Lint
        caches:
          - node
        script:
          - yarn install
          - yarn run lint
    - step:
        name: Test
        caches:
          - node
        script:
          - yarn global add tap-xunit codecov
          - export PATH="$PATH:$(yarn global bin)"
          - mkdir -p test-reports
          - yarn run test | tap-xunit > ./test-reports/xunit.xml
          - yarn nyc report --reporter=text-lcov > coverage.lcov
          - codecov
